[versions]
mapstruct = "1.6.3"
mapstruct-spring = "2.0.0"
springBoot = "4.0.1"

[libraries]
gradle-plugin-release = { group = "pl.allegro.tech.build", name = "axion-release-plugin", version = "1.21.1" }
gradle-plugin-spotless = { group = "com.diffplug.spotless", name = "spotless-plugin-gradle", version = "8.1.0" }
mapstruct-core = { group = "org.mapstruct", name = "mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { group = "org.mapstruct", name = "mapstruct-processor", version.ref = "mapstruct" }
mapstruct-springAnnotations = { group = "org.mapstruct.extensions.spring", name = "mapstruct-spring-annotations", version.ref = "mapstruct-spring" }
mapstruct-springExtensions = { group = "org.mapstruct.extensions.spring", name = "mapstruct-spring-extensions", version.ref = "mapstruct-spring" }
springBootDependencies = { group = "org.springframework.boot", name = "spring-boot-dependencies", version.ref = "springBoot" }
springdoc-openapiStarterWebmvcUi = { group = "org.springdoc", name = "springdoc-openapi-starter-webmvc-ui", version = "3.0.1" }

[plugins]
graalvm = { id = "org.graalvm.buildtools.native", version = "0.11.3" }
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-nullability = { id = "io.spring.nullability", version = "0.0.9" }
versions = { id = "com.github.ben-manes.versions", version = "0.53.0" }
