[versions]

[libraries]
gradle-plugin-release = { group = "pl.allegro.tech.build", name = "axion-release-plugin", version = "1.19.0" }
gradle-plugin-spotless = { group = "com.diffplug.spotless", name = "spotless-plugin-gradle", version = "7.2.1" }
springdoc-starter-webmvc-ui = { group = "org.springdoc", name = "springdoc-openapi-starter-webmvc-ui", version = "2.8.9" }

[plugins]
graalvm = { id = "org.graalvm.buildtools.native", version = "0.10.6" }
spring-boot = { id = "org.springframework.boot", version = "3.5.8" }
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.7" }
versions = { id = "com.github.ben-manes.versions", version = "0.52.0" }
